### ISSUE TITLE
[NeMO User Issue]: Portal and ftp unavailable

### ISSUE THREAD

**Issue by gennadyFauna** [nemoarchive/issues#6]
### Project

Other

### What category best fits your issue?

Accessing public files

### Issue

The usual data access interface (http://data.nemoarchive.org/) seems to be down or restricted, and the links to it from https://nemoarchive.org/data/ and https://nemoarchive.org/resources/data-download are broken. Across browsers, the data dashboard (https://portal.nemoarchive.org/) is stuck loading (?) and cannot be used. I would tremendously appreciate if the maintainers could say something about the planned maintenance schedule, or point me to some other source that hosts updates.

### This ticket contains only public information

- [x] There is no personally identifiable or restricted information included in this ticket

**Comment by gennadyFauna** [comment]
Looks like ftp is up as of yesterday, but the data dashboard still cannot be used.

**Comment by JPReceveur** [comment]
Sorry for the delay in responding, yes the http site issue is fixed, we're still working an update to the data portal.

**Comment by gennadyFauna** [comment]
Http seems to be inaccessible again and the dashboard still cannot be used.

-------

A few hours later: 
but http is accessible now when it was not this morning. Could I get any more info on this? Incidental instability or scheduled maintenance?
